package com.pactera.pacteramap.business.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_INFO.
 */
public class MessageInfo {

    private Long id;
    private String date;
    private String avatarUrl;
    private String messageTitle;
    private String messageContent;
    private String messageFrom;
    private String userName;
    private String messageStates;

    public MessageInfo() {
    }

    public MessageInfo(Long id) {
        this.id = id;
    }

    public MessageInfo(Long id, String date, String avatarUrl, String messageTitle, String messageContent, String messageFrom, String userName, String messageStates) {
        this.id = id;
        this.date = date;
        this.avatarUrl = avatarUrl;
        this.messageTitle = messageTitle;
        this.messageContent = messageContent;
        this.messageFrom = messageFrom;
        this.userName = userName;
        this.messageStates = messageStates;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getMessageTitle() {
        return messageTitle;
    }

    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getMessageFrom() {
        return messageFrom;
    }

    public void setMessageFrom(String messageFrom) {
        this.messageFrom = messageFrom;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getMessageStates() {
        return messageStates;
    }

    public void setMessageStates(String messageStates) {
        this.messageStates = messageStates;
    }

}
