package com.pactera.pacteramap.business.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORK_TRACK.
 */
public class WorkTrack {

    private Long id;
    private String date;
    private String userName;
    private String userImei;
    private String longitude;
    private String latitude;
    private String isMark;
    private String markIndex;
    private String desc;

    public WorkTrack() {
    }

    public WorkTrack(Long id) {
        this.id = id;
    }

    public WorkTrack(Long id, String date, String userName, String userImei, String longitude, String latitude, String isMark, String markIndex, String desc) {
        this.id = id;
        this.date = date;
        this.userName = userName;
        this.userImei = userImei;
        this.longitude = longitude;
        this.latitude = latitude;
        this.isMark = isMark;
        this.markIndex = markIndex;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserImei() {
        return userImei;
    }

    public void setUserImei(String userImei) {
        this.userImei = userImei;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getIsMark() {
        return isMark;
    }

    public void setIsMark(String isMark) {
        this.isMark = isMark;
    }

    public String getMarkIndex() {
        return markIndex;
    }

    public void setMarkIndex(String markIndex) {
        this.markIndex = markIndex;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
