package com.pactera.pacteramap.business.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pactera.pacteramap.business.database.bean.WorkTrack;

import com.pactera.pacteramap.business.database.dao.WorkTrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workTrackDaoConfig;

    private final WorkTrackDao workTrackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workTrackDaoConfig = daoConfigMap.get(WorkTrackDao.class).clone();
        workTrackDaoConfig.initIdentityScope(type);

        workTrackDao = new WorkTrackDao(workTrackDaoConfig, this);

        registerDao(WorkTrack.class, workTrackDao);
    }
    
    public void clear() {
        workTrackDaoConfig.getIdentityScope().clear();
    }

    public WorkTrackDao getWorkTrackDao() {
        return workTrackDao;
    }

}
